const sampledata = [
  {
    "id": 1,
    "image": "http://dummyimage.com/106x246.png/ff4444/ffffff",
    "productcode": "76420-780",
    "name": "Syrup - Golden, Lyles",
    "description": "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "department": "Vegetarian",
    "price": 51,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 2,
    "image": "http://dummyimage.com/223x202.jpg/cc0000/ffffff",
    "productcode": "35418-750",
    "name": "Nantucket Orange Juice",
    "description": "Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "department": "Healthy Food",
    "price": 48,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 3,
    "image": "http://dummyimage.com/162x156.jpg/cc0000/ffffff",
    "productcode": "63629-3211",
    "name": "Bread - Sticks, Thin, Plain",
    "description": "Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",
    "department": "Vegan",
    "price": 100,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 4,
    "image": "http://dummyimage.com/180x174.jpg/dddddd/000000",
    "productcode": "0338-9542",
    "name": "Pepper - Orange",
    "description": "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    "department": "Vegan",
    "price": 40,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 5,
    "image": "http://dummyimage.com/229x223.png/dddddd/000000",
    "productcode": "0781-3166",
    "name": "Cocoa Powder - Natural",
    "description": "Maecenas tincidunt lacus at velit.",
    "department": "Healthy Food",
    "price": 80,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 6,
    "image": "http://dummyimage.com/228x217.bmp/dddddd/000000",
    "productcode": "50382-011",
    "name": "Island Oasis - Wildberry",
    "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    "department": "Daily Food",
    "price": 1,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 7,
    "image": "http://dummyimage.com/180x166.bmp/cc0000/ffffff",
    "productcode": "10096-0311",
    "name": "Vegetable - Base",
    "description": "Nullam porttitor lacus at turpis.",
    "department": "Daily Food",
    "price": 57,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 8,
    "image": "http://dummyimage.com/215x215.png/cc0000/ffffff",
    "productcode": "67544-023",
    "name": "Zucchini - Yellow",
    "description": "Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
    "department": "Vegan",
    "price": 22,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 9,
    "image": "http://dummyimage.com/234x150.bmp/5fa2dd/ffffff",
    "productcode": "51672-1322",
    "name": "Flour - Cake",
    "description": "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "department": "Healthy Food",
    "price": 90,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 10,
    "image": "http://dummyimage.com/180x250.png/5fa2dd/ffffff",
    "productcode": "0548-3015",
    "name": "Salmon - Smoked, Sliced",
    "description": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    "department": "Healthy Food",
    "price": 82,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 11,
    "image": "http://dummyimage.com/196x111.bmp/cc0000/ffffff",
    "productcode": "61300-0001",
    "name": "Oxtail - Cut",
    "description": "Proin risus.",
    "department": "Daily Food",
    "price": 51,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 12,
    "image": "http://dummyimage.com/196x100.jpg/5fa2dd/ffffff",
    "productcode": "51672-4063",
    "name": "Walkers Special Old Whiskey",
    "description": "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    "department": "Healthy Food",
    "price": 4,
    "currency": "EUR",
    "store": "Estonia",
    "instock": false
  },
  {
    "id": 13,
    "image": "http://dummyimage.com/154x199.png/5fa2dd/ffffff",
    "productcode": "13630-0051",
    "name": "Onions - Cippolini",
    "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.",
    "department": "Vegan",
    "price": 15,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 14,
    "image": "http://dummyimage.com/169x164.bmp/dddddd/000000",
    "productcode": "53329-061",
    "name": "Bread - Rye",
    "description": "In hac habitasse platea dictumst.",
    "department": "Vegan",
    "price": 100,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 15,
    "image": "http://dummyimage.com/205x188.jpg/dddddd/000000",
    "productcode": "17089-242",
    "name": "Wine - White, Mosel Gold",
    "description": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.",
    "department": "Vegetarian",
    "price": 5,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 16,
    "image": "http://dummyimage.com/247x103.jpg/ff4444/ffffff",
    "productcode": "49884-056",
    "name": "Appetizer - Mini Egg Roll, Shrimp",
    "description": "Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    "department": "Vegan",
    "price": 57,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 17,
    "image": "http://dummyimage.com/159x199.jpg/cc0000/ffffff",
    "productcode": "62935-302",
    "name": "Lamb Rack - Ontario",
    "description": "Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
    "department": "Healthy Food",
    "price": 30,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 18,
    "image": "http://dummyimage.com/211x110.bmp/ff4444/ffffff",
    "productcode": "63713-461",
    "name": "Soup Campbells Mexicali Tortilla",
    "description": "Vestibulum sed magna at nunc commodo placerat.",
    "department": "Vegetarian",
    "price": 64,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 19,
    "image": "http://dummyimage.com/187x207.jpg/cc0000/ffffff",
    "productcode": "0054-0404",
    "name": "Extract - Almond",
    "description": "Proin risus. Praesent lectus.",
    "department": "Daily Food",
    "price": 58,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 20,
    "image": "http://dummyimage.com/181x217.bmp/5fa2dd/ffffff",
    "productcode": "37808-698",
    "name": "Lotus Root",
    "description": "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
    "department": "Vegetarian",
    "price": 38,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 21,
    "image": "http://dummyimage.com/226x235.bmp/dddddd/000000",
    "productcode": "41167-4310",
    "name": "Cheese - Cambozola",
    "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    "department": "Vegetarian",
    "price": 21,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 22,
    "image": "http://dummyimage.com/140x132.png/dddddd/000000",
    "productcode": "16590-863",
    "name": "Appetizer - Seafood Assortment",
    "description": "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    "department": "Vegetarian",
    "price": 2,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 23,
    "image": "http://dummyimage.com/165x107.jpg/cc0000/ffffff",
    "productcode": "10237-754",
    "name": "Squash - Sunburst",
    "description": "Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
    "department": "Vegan",
    "price": 27,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 24,
    "image": "http://dummyimage.com/234x229.png/cc0000/ffffff",
    "productcode": "0268-6526",
    "name": "Wine - Cava Aria Estate Brut",
    "description": "Aliquam erat volutpat. In congue. Etiam justo.",
    "department": "Vegetarian",
    "price": 47,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 25,
    "image": "http://dummyimage.com/140x149.jpg/dddddd/000000",
    "productcode": "68788-9790",
    "name": "Fruit Salad Deluxe",
    "description": "Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.",
    "department": "Healthy Food",
    "price": 94,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 26,
    "image": "http://dummyimage.com/143x219.bmp/5fa2dd/ffffff",
    "productcode": "49909-005",
    "name": "Cookies - Englishbay Oatmeal",
    "description": "Donec semper sapien a libero.",
    "department": "Healthy Food",
    "price": 11,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 27,
    "image": "http://dummyimage.com/148x209.jpg/cc0000/ffffff",
    "productcode": "0096-0741",
    "name": "Pork - Back, Long Cut, Boneless",
    "description": "Aenean lectus. Pellentesque eget nunc.",
    "department": "Healthy Food",
    "price": 68,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 28,
    "image": "http://dummyimage.com/250x232.jpg/ff4444/ffffff",
    "productcode": "36987-1668",
    "name": "Apricots - Dried",
    "description": "In quis justo.",
    "department": "Vegetarian",
    "price": 22,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 29,
    "image": "http://dummyimage.com/133x192.bmp/ff4444/ffffff",
    "productcode": "76214-034",
    "name": "Dragon Fruit",
    "description": "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    "department": "Healthy Food",
    "price": 27,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 30,
    "image": "http://dummyimage.com/233x214.png/5fa2dd/ffffff",
    "productcode": "0093-1026",
    "name": "Canada Dry",
    "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    "department": "Daily Food",
    "price": 36,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 31,
    "image": "http://dummyimage.com/175x144.bmp/5fa2dd/ffffff",
    "productcode": "0268-6648",
    "name": "Vinegar - Balsamic",
    "description": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    "department": "Vegetarian",
    "price": 15,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 32,
    "image": "http://dummyimage.com/235x213.jpg/5fa2dd/ffffff",
    "productcode": "63402-511",
    "name": "Dikon",
    "description": "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.",
    "department": "Daily Food",
    "price": 85,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 33,
    "image": "http://dummyimage.com/229x102.bmp/dddddd/000000",
    "productcode": "36987-2688",
    "name": "Mushroom - Lg - Cello",
    "description": "Aenean sit amet justo. Morbi ut odio.",
    "department": "Healthy Food",
    "price": 93,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 34,
    "image": "http://dummyimage.com/198x112.jpg/dddddd/000000",
    "productcode": "55289-302",
    "name": "Pepper - Red Chili",
    "description": "Etiam justo. Etiam pretium iaculis justo.",
    "department": "Daily Food",
    "price": 93,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 35,
    "image": "http://dummyimage.com/188x204.png/cc0000/ffffff",
    "productcode": "36987-1586",
    "name": "Spice - Paprika",
    "description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    "department": "Healthy Food",
    "price": 68,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 36,
    "image": "http://dummyimage.com/126x186.bmp/5fa2dd/ffffff",
    "productcode": "36987-2607",
    "name": "Trout - Rainbow, Frozen",
    "description": "Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    "department": "Healthy Food",
    "price": 7,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 37,
    "image": "http://dummyimage.com/198x226.png/5fa2dd/ffffff",
    "productcode": "54575-969",
    "name": "Carrots - Purple, Organic",
    "description": "Nulla tempus.",
    "department": "Daily Food",
    "price": 47,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 38,
    "image": "http://dummyimage.com/155x201.png/dddddd/000000",
    "productcode": "63629-3386",
    "name": "Cheese - Havarti, Salsa",
    "description": "Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.",
    "department": "Vegan",
    "price": 38,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 39,
    "image": "http://dummyimage.com/238x125.png/ff4444/ffffff",
    "productcode": "36987-2707",
    "name": "Bread - Hot Dog Buns",
    "description": "Proin at turpis a pede posuere nonummy.",
    "department": "Vegetarian",
    "price": 47,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 40,
    "image": "http://dummyimage.com/200x224.bmp/ff4444/ffffff",
    "productcode": "14743-103",
    "name": "Dasheen",
    "description": "Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
    "department": "Daily Food",
    "price": 38,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 41,
    "image": "http://dummyimage.com/146x203.bmp/cc0000/ffffff",
    "productcode": "43353-656",
    "name": "Venison - Ground",
    "description": "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    "department": "Daily Food",
    "price": 64,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 42,
    "image": "http://dummyimage.com/140x118.png/ff4444/ffffff",
    "productcode": "0093-0263",
    "name": "Cheese - Grana Padano",
    "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    "department": "Vegetarian",
    "price": 66,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 43,
    "image": "http://dummyimage.com/245x182.jpg/5fa2dd/ffffff",
    "productcode": "64679-810",
    "name": "Veal - Kidney",
    "description": "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    "department": "Vegan",
    "price": 41,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 44,
    "image": "http://dummyimage.com/200x170.bmp/5fa2dd/ffffff",
    "productcode": "63261-250",
    "name": "Yoplait - Strawbrasp Peac",
    "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    "department": "Vegetarian",
    "price": 73,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 45,
    "image": "http://dummyimage.com/170x129.bmp/5fa2dd/ffffff",
    "productcode": "62018-001",
    "name": "Tea Leaves - Oolong",
    "description": "Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    "department": "Daily Food",
    "price": 79,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 46,
    "image": "http://dummyimage.com/217x168.bmp/cc0000/ffffff",
    "productcode": "60512-2003",
    "name": "Soup - Boston Clam Chowder",
    "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    "department": "Healthy Food",
    "price": 43,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 47,
    "image": "http://dummyimage.com/103x114.bmp/ff4444/ffffff",
    "productcode": "65044-4702",
    "name": "Blouse / Shirt / Sweater",
    "description": "Maecenas tincidunt lacus at velit.",
    "department": "Healthy Food",
    "price": 14,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 48,
    "image": "http://dummyimage.com/148x172.bmp/5fa2dd/ffffff",
    "productcode": "68001-116",
    "name": "Oil - Canola",
    "description": "Quisque id justo sit amet sapien dignissim vestibulum.",
    "department": "Vegan",
    "price": 43,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 49,
    "image": "http://dummyimage.com/103x240.jpg/5fa2dd/ffffff",
    "productcode": "65841-729",
    "name": "Beef - Diced",
    "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    "department": "Healthy Food",
    "price": 44,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 50,
    "image": "http://dummyimage.com/139x197.jpg/cc0000/ffffff",
    "productcode": "63739-557",
    "name": "Chervil - Fresh",
    "description": "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.",
    "department": "Vegan",
    "price": 38,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 51,
    "image": "http://dummyimage.com/237x151.jpg/ff4444/ffffff",
    "productcode": "41167-0105",
    "name": "Mushroom - Lg - Cello",
    "description": "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.",
    "department": "Vegan",
    "price": 7,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 52,
    "image": "http://dummyimage.com/121x130.png/cc0000/ffffff",
    "productcode": "0703-5656",
    "name": "Pastry - Mini French Pastries",
    "description": "Integer ac leo. Pellentesque ultrices mattis odio.",
    "department": "Vegetarian",
    "price": 22,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 53,
    "image": "http://dummyimage.com/243x154.jpg/cc0000/ffffff",
    "productcode": "33342-037",
    "name": "Flour - Whole Wheat",
    "description": "Sed sagittis.",
    "department": "Daily Food",
    "price": 99,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 54,
    "image": "http://dummyimage.com/206x242.bmp/cc0000/ffffff",
    "productcode": "68479-013",
    "name": "Peppercorns - Pink",
    "description": "In hac habitasse platea dictumst.",
    "department": "Vegetarian",
    "price": 57,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 55,
    "image": "http://dummyimage.com/192x158.png/cc0000/ffffff",
    "productcode": "49790-001",
    "name": "Plastic Arrow Stir Stick",
    "description": "Phasellus sit amet erat. Nulla tempus.",
    "department": "Healthy Food",
    "price": 67,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 56,
    "image": "http://dummyimage.com/228x107.png/dddddd/000000",
    "productcode": "50268-265",
    "name": "Soap - Mr.clean Floor Soap",
    "description": "Phasellus id sapien in sapien iaculis congue.",
    "department": "Vegan",
    "price": 77,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 57,
    "image": "http://dummyimage.com/204x156.png/dddddd/000000",
    "productcode": "55648-312",
    "name": "Coffee - Decafenated",
    "description": "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    "department": "Daily Food",
    "price": 14,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 58,
    "image": "http://dummyimage.com/174x161.png/ff4444/ffffff",
    "productcode": "53808-0888",
    "name": "Beer - Sleemans Cream Ale",
    "description": "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    "department": "Healthy Food",
    "price": 24,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 59,
    "image": "http://dummyimage.com/131x160.jpg/dddddd/000000",
    "productcode": "0067-2021",
    "name": "Wine - Malbec Trapiche Reserve",
    "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.",
    "department": "Vegan",
    "price": 62,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 60,
    "image": "http://dummyimage.com/179x250.png/dddddd/000000",
    "productcode": "52584-321",
    "name": "Vinegar - Raspberry",
    "description": "Duis bibendum.",
    "department": "Healthy Food",
    "price": 81,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 61,
    "image": "http://dummyimage.com/190x166.bmp/ff4444/ffffff",
    "productcode": "24236-364",
    "name": "Cup - 4oz Translucent",
    "description": "Maecenas rhoncus aliquam lacus.",
    "department": "Vegan",
    "price": 67,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 62,
    "image": "http://dummyimage.com/190x185.bmp/ff4444/ffffff",
    "productcode": "0006-0757",
    "name": "Momiji Oroshi Chili Sauce",
    "description": "Praesent lectus.",
    "department": "Vegetarian",
    "price": 98,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 63,
    "image": "http://dummyimage.com/200x171.jpg/dddddd/000000",
    "productcode": "49817-0053",
    "name": "Pork Casing",
    "description": "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
    "department": "Vegetarian",
    "price": 69,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 64,
    "image": "http://dummyimage.com/201x162.png/5fa2dd/ffffff",
    "productcode": "0591-0408",
    "name": "Bagel - 12 Grain Preslice",
    "description": "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    "department": "Daily Food",
    "price": 83,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 65,
    "image": "http://dummyimage.com/151x156.png/ff4444/ffffff",
    "productcode": "59779-182",
    "name": "Lady Fingers",
    "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.",
    "department": "Vegetarian",
    "price": 68,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 66,
    "image": "http://dummyimage.com/215x164.png/5fa2dd/ffffff",
    "productcode": "51523-001",
    "name": "Ecolab - Hobart Upr Prewash Arm",
    "description": "Nulla ut erat id mauris vulputate elementum.",
    "department": "Daily Food",
    "price": 59,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 67,
    "image": "http://dummyimage.com/204x218.bmp/ff4444/ffffff",
    "productcode": "59995-001",
    "name": "Pork - Back Ribs",
    "description": "Praesent lectus.",
    "department": "Vegetarian",
    "price": 12,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 68,
    "image": "http://dummyimage.com/163x239.bmp/cc0000/ffffff",
    "productcode": "11822-0004",
    "name": "Bag Clear 10 Lb",
    "description": "Fusce consequat.",
    "department": "Vegan",
    "price": 53,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 69,
    "image": "http://dummyimage.com/140x160.png/dddddd/000000",
    "productcode": "57955-0128",
    "name": "Cheese - Oka",
    "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius.",
    "department": "Vegetarian",
    "price": 66,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 70,
    "image": "http://dummyimage.com/101x101.bmp/5fa2dd/ffffff",
    "productcode": "49643-018",
    "name": "Pastry - Apple Muffins - Mini",
    "description": "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    "department": "Vegetarian",
    "price": 42,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 71,
    "image": "http://dummyimage.com/169x235.png/ff4444/ffffff",
    "productcode": "61957-0117",
    "name": "Sherbet - Raspberry",
    "description": "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    "department": "Vegan",
    "price": 91,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 72,
    "image": "http://dummyimage.com/160x187.jpg/5fa2dd/ffffff",
    "productcode": "0009-0225",
    "name": "Coke - Diet, 355 Ml",
    "description": "Nam dui.",
    "department": "Daily Food",
    "price": 85,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 73,
    "image": "http://dummyimage.com/101x113.jpg/dddddd/000000",
    "productcode": "51079-460",
    "name": "Long Island Ice Tea",
    "description": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.",
    "department": "Daily Food",
    "price": 43,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 74,
    "image": "http://dummyimage.com/126x201.png/dddddd/000000",
    "productcode": "0002-4771",
    "name": "Chinese Foods - Plain Fried Rice",
    "description": "Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.",
    "department": "Vegan",
    "price": 24,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 75,
    "image": "http://dummyimage.com/189x193.png/dddddd/000000",
    "productcode": "36987-3171",
    "name": "Water, Tap",
    "description": "Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
    "department": "Vegan",
    "price": 82,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 76,
    "image": "http://dummyimage.com/110x133.png/cc0000/ffffff",
    "productcode": "24385-036",
    "name": "Juice - Clam, 46 Oz",
    "description": "In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.",
    "department": "Vegetarian",
    "price": 21,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 77,
    "image": "http://dummyimage.com/111x185.png/dddddd/000000",
    "productcode": "51079-223",
    "name": "Turkey - Whole, Fresh",
    "description": "Suspendisse accumsan tortor quis turpis.",
    "department": "Healthy Food",
    "price": 44,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 78,
    "image": "http://dummyimage.com/210x171.png/cc0000/ffffff",
    "productcode": "29500-8030",
    "name": "Wine - White, Cooking",
    "description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    "department": "Daily Food",
    "price": 36,
    "currency": "EUR",
    "store": "Estonia",
    "instock": false
  },
  {
    "id": 79,
    "image": "http://dummyimage.com/250x126.png/5fa2dd/ffffff",
    "productcode": "0363-2102",
    "name": "Honey - Comb",
    "description": "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    "department": "Healthy Food",
    "price": 99,
    "currency": "EUR",
    "store": "Estonia",
    "instock": true
  },
  {
    "id": 80,
    "image": "http://dummyimage.com/222x128.jpg/5fa2dd/ffffff",
    "productcode": "68462-115",
    "name": "Wine - Chateauneuf Du Pape",
    "description": "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.",
    "department": "Vegan",
    "price": 52,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 81,
    "image": "http://dummyimage.com/177x208.png/ff4444/ffffff",
    "productcode": "0363-0534",
    "name": "Blueberries - Frozen",
    "description": "Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    "department": "Vegetarian",
    "price": 15,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 82,
    "image": "http://dummyimage.com/225x205.bmp/ff4444/ffffff",
    "productcode": "64980-175",
    "name": "Sauce - Apple, Unsweetened",
    "description": "Pellentesque at nulla.",
    "department": "Healthy Food",
    "price": 40,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 83,
    "image": "http://dummyimage.com/177x127.png/ff4444/ffffff",
    "productcode": "42998-963",
    "name": "Truffle - Peelings",
    "description": "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.",
    "department": "Daily Food",
    "price": 16,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 84,
    "image": "http://dummyimage.com/153x206.bmp/cc0000/ffffff",
    "productcode": "68472-092",
    "name": "Sprouts - Baby Pea Tendrils",
    "description": "Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.",
    "department": "Vegetarian",
    "price": 34,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 85,
    "image": "http://dummyimage.com/233x157.jpg/dddddd/000000",
    "productcode": "36987-1522",
    "name": "Cheese - Boursin, Garlic / Herbs",
    "description": "Mauris sit amet eros.",
    "department": "Healthy Food",
    "price": 39,
    "currency": "EUR",
    "store": "Estonia",
    "instock": false
  },
  {
    "id": 86,
    "image": "http://dummyimage.com/211x116.bmp/5fa2dd/ffffff",
    "productcode": "0121-4793",
    "name": "Ecolab - Hand Soap Form Antibac",
    "description": "Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.",
    "department": "Vegetarian",
    "price": 31,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 87,
    "image": "http://dummyimage.com/127x154.jpg/dddddd/000000",
    "productcode": "49953-2801",
    "name": "Soup - Campbells Chili Veg",
    "description": "In congue.",
    "department": "Vegan",
    "price": 8,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 88,
    "image": "http://dummyimage.com/145x214.png/5fa2dd/ffffff",
    "productcode": "58118-3541",
    "name": "Longos - Grilled Veg Sandwiches",
    "description": "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.",
    "department": "Healthy Food",
    "price": 55,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 89,
    "image": "http://dummyimage.com/109x219.bmp/cc0000/ffffff",
    "productcode": "50845-0048",
    "name": "Squeeze Bottle",
    "description": "Aenean auctor gravida sem.",
    "department": "Daily Food",
    "price": 70,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 90,
    "image": "http://dummyimage.com/108x230.png/5fa2dd/ffffff",
    "productcode": "10356-351",
    "name": "Beef - Striploin Aa",
    "description": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    "department": "Vegan",
    "price": 79,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 91,
    "image": "http://dummyimage.com/126x171.bmp/cc0000/ffffff",
    "productcode": "0228-2530",
    "name": "Irish Cream - Baileys",
    "description": "Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.",
    "department": "Vegetarian",
    "price": 56,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 92,
    "image": "http://dummyimage.com/154x143.bmp/ff4444/ffffff",
    "productcode": "60977-144",
    "name": "Chicken - Whole",
    "description": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.",
    "department": "Daily Food",
    "price": 29,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 93,
    "image": "http://dummyimage.com/177x156.jpg/dddddd/000000",
    "productcode": "60429-163",
    "name": "Pork - Backs - Boneless",
    "description": "Nam nulla.",
    "department": "Vegan",
    "price": 66,
    "currency": "EUR",
    "store": "Estonia",
    "instock": false
  },
  {
    "id": 94,
    "image": "http://dummyimage.com/214x153.png/ff4444/ffffff",
    "productcode": "55154-9427",
    "name": "Celery",
    "description": "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.",
    "department": "Daily Food",
    "price": 49,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 95,
    "image": "http://dummyimage.com/127x239.png/cc0000/ffffff",
    "productcode": "13537-284",
    "name": "Sour Puss - Tangerine",
    "description": "Integer non velit.",
    "department": "Vegan",
    "price": 40,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 96,
    "image": "http://dummyimage.com/153x250.jpg/ff4444/ffffff",
    "productcode": "47632-0029",
    "name": "Scallops 60/80 Iqf",
    "description": "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
    "department": "Daily Food",
    "price": 8,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 97,
    "image": "http://dummyimage.com/132x108.jpg/cc0000/ffffff",
    "productcode": "0904-6296",
    "name": "Chicken - Whole Roasting",
    "description": "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    "department": "Vegan",
    "price": 17,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
  {
    "id": 98,
    "image": "http://dummyimage.com/125x196.jpg/dddddd/000000",
    "productcode": "65044-1061",
    "name": "Melon - Watermelon, Seedless",
    "description": "Maecenas pulvinar lobortis est.",
    "department": "Vegan",
    "price": 88,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 99,
    "image": "http://dummyimage.com/171x150.jpg/dddddd/000000",
    "productcode": "63629-5311",
    "name": "Oneshot Automatic Soap System",
    "description": "Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.",
    "department": "Daily Food",
    "price": 95,
    "currency": "EUR",
    "store": "Finland",
    "instock": false
  },
  {
    "id": 100,
    "image": "http://dummyimage.com/122x238.jpg/5fa2dd/ffffff",
    "productcode": "0179-0091",
    "name": "Amaretto",
    "description": "Phasellus sit amet erat. Nulla tempus.",
    "department": "Vegan",
    "price": 8,
    "currency": "EUR",
    "store": "Finland",
    "instock": true
  },
];

const input = {
	entities: ['products', 'stores', 'departments'],
	headers: {
		'Accept': 'application/json',
		'Content-Type': 'application/json'
	},
	data: {
		departments: ["Vegetarian", "Healthy Food", "Vegan", "Daily Food"],
		countries: [
			{
				"name": "Finland",
				"country": "FINLAND",
			},
			{
				"name": "Estonia",
				"country": "ESTONIA",
			},
		],
	}
};


const requestHelper = async (promises) => {
	return Promise.all([...promises])
		.then(result => Promise.all(result.map(v => v.json())))
		.then(result => result);
}

const request = (data, url, method) => fetch(`http://localhost:8080/api/${url}`, {
	method,
	headers: input.headers,
	body: JSON.stringify(data),
});

const add = (data, url) => request(data, `${url}/add`, 'POST');

const deleteAll = async () => requestHelper(input.entities.map(entity => request({}, `${entity}/deleteAll`, 'DELETE')));
deleteAll();

const countryList = await requestHelper(
	input.data.countries
		.map(async item => (add(item, 'stores')))
);
const departmentList = await requestHelper(
	input.data.departments
		.map(async department => add({ "name": department }, 'departments'))
);

const findId = (targetName, list) => list.find(({ name }) => name === targetName);

const getNewData = (props) => ({
	"image": [{
		"url": props.image
	}],
	"department": {
		"id": findId(props.department, departmentList).id
	},
	"price": props.price,
	"currency": props.currency,
	"inStock": props.instock,
	"productCode": props.productcode,
	"description": props.description,
	"store": {
		"id": findId(props.store, countryList).id
	},
	"name": props.name,
});

const newProductList = await requestHelper(
	sampledata
		.map(async productOldData => add(getNewData(productOldData), 'products'))
);
